//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MotionMonitor.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_MotionMonitorTYPE           130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_DIALOG_SERIAL_EDITOR        310
#define IDD_DIALOG_3D                   311
#define IDD_DIALOG_SERIAL_GRAPH         312
#define IDD_DIALOG_UDP_GRAPH            315
#define IDD_DIALOG_UDP_EDITOR           317
#define IDD_DIALOG_MOTION_OUTPUT        318
#define IDD_DIALOG_MOTION_CONTROL       319
#define IDD_DIALOG_MOTION_INPUT         320
#define IDD_DIALOG_X2GRAPH              322
#define IDD_DIALOG_JOYSTICK             323
#define IDD_DIALOG_MWAVE                324
#define IDD_DIALOG_MIXING               326
#define IDC_CHECK_FIXEDMODE             1000
#define IDC_EDIT_COMMAND                1001
#define IDC_BUTTON_HELP                 1002
#define IDC_BUTTON_UPDATE               1003
#define IDC_STATIC1                     1004
#define IDC_RICHEDIT_SERIAL             1005
#define IDC_BUTTON_PAUSE                1005
#define IDC_STATIC_FASTTEXT             1006
#define IDC_RADIO_MODE                  1007
#define IDC_RADIO_FAST                  1008
#define IDC_EDIT1                       1008
#define IDC_BUTTON_UDP_SERVER_BIND      1009
#define IDC_STATIC_PACKET               1010
#define IDC_STATIC_PACKET_COUNT         1011
#define IDC_MFCEDITBROWSE_XMLPATH       1012
#define IDC_RICHEDIT2_UDP_LOG           1013
#define IDC_EDIT_SERVER_PORT            1014
#define IDC_BUTTON_CLEAR                1015
#define IDC_CHECK_PRINT_PACKET          1016
#define IDC_COMBO_COM_PORTS             1017
#define IDC_COMBO_COM_BAUDRATE          1018
#define IDC_BUTTON_CONNECT              1019
#define IDC_BUTTON_START_SEND_MOTION    1020
#define IDC_RICHEDIT2_LOG               1021
#define IDC_RICHEDIT2_OUTPUT_LOG        1022
#define IDC_STATIC_GRAPH                1024
#define IDC_SLIDER_YAW_DERIVATION       1026
#define IDC_EDIT_YAW_DERIVATION         1027
#define IDC_SLIDER_PITCH_PROPORTION     1028
#define IDC_BUTTON_START                1028
#define IDC_EDIT_PITCH_PROPORTION       1029
#define IDC_BUTTON_STOP                 1029
#define IDC_SLIDER_YAW_INTEGRAL         1030
#define IDC_BUTTON_ORIGIN               1030
#define IDC_EDIT_YAW_INTEGRAL           1031
#define IDC_BUTTON_EMERGENCY            1031
#define IDC_SLIDER_ROLL_PROPORTION      1032
#define IDC_BUTTON_SERVO_ON             1032
#define IDC_EDIT_ROLL_PROPORTION        1033
#define IDC_BUTTON_SERVO_OFF            1033
#define IDC_SLIDER_YAW_PROPORTION       1034
#define IDC_CHECK1                      1034
#define IDC_EDIT_YAW_PROPORTION         1035
#define IDC_SLIDER_PITCH_INTEGRAL       1036
#define IDC_SLIDER_YAW                  1036
#define IDC_EDIT_PITCH_INTEGRAL         1037
#define IDC_EDIT_YAW                    1037
#define IDC_SLIDER_YAW_SCALE2           1038
#define IDC_SLIDER_PITCH                1038
#define IDC_EDIT_YAW_SCALE2             1039
#define IDC_EDIT_PITCH                  1039
#define IDC_SLIDER_PITCH_DERIVATION     1040
#define IDC_SLIDER_ROLL                 1040
#define IDC_EDIT_PITCH_DERIVATION       1041
#define IDC_EDIT_ROLL                   1041
#define IDC_SLIDER_ROLL_INTEGRAL        1042
#define IDC_STATIC_YAW                  1042
#define IDC_EDIT_ROLL_INTEGRAL          1043
#define IDC_STATIC_PITCH                1043
#define IDC_SLIDER_ROLL_DERIVATION      1044
#define IDC_STATIC_ROLL                 1044
#define IDC_EDIT_ROLL_DERIVATION        1045
#define IDC_SLIDER_YAW_OFFSET           1045
#define IDC_SLIDER_PITCH_SCALE2         1046
#define IDC_STATIC_YAW2                 1046
#define IDC_EDIT_PITCH_SCALE2           1047
#define IDC_EDIT_YAW_OFFSET             1047
#define IDC_SLIDER_ROLL_SCALE2          1048
#define IDC_SLIDER_PITCH_OFFSET         1048
#define IDC_EDIT_ROLL_SCALE2            1049
#define IDC_STATIC_PITCH2               1049
#define IDC_EDIT_PITCH_OFFSET           1050
#define IDC_SLIDER_ROLL_OFFSET          1051
#define IDC_STATIC_ROLL2                1052
#define IDC_EDIT_ROLL_OFFSET            1053
#define IDC_BUTTON_RECORD               1054
#define IDC_BUTTON_MOTION_OUTPUT_START  1055
#define IDC_SLIDER_HEAVE_OFFSET         1056
#define IDC_STATIC_ROLL3                1057
#define IDC_TREE_FILE                   1057
#define IDC_EDIT_HEAVE_OFFSET           1058
#define IDC_BUTTON_PLAY                 1058
#define IDC_SLIDER_HEAVE                1059
#define IDC_STATIC_HEAVE                1060
#define IDC_RICHEDIT2_COMMAND           1060
#define IDC_EDIT_HEAVE                  1061
#define IDC_BUTTON_REFRESH              1066
#define IDC_STATIC_GROUP                1067

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        328
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1070
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
